import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cheeseculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1>Hello Cheese!</h1>
      </main>
    </div>
  )
}
